export const demoProducts = [
  {
    id: 'demo-goku',
    slug: 'figura-armable-goku-super-saiyan',
    name: 'Figura armable Goku Super Saiyan',
    price: 16000,
    previousPrice: 19000,
    character: 'Goku',
    presentation: 'Figura individual 8cm',
    pieces: 118,
    isLimitedEdition: false,
    description: 'Arma tu propio Goku Super Saiyan estilo bloques, compatible con otras marcas de bloques. Ideal para coleccionar y regalar.',
    brand: { name: 'Dragon Ball' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 25 },
    images: [],
  },
  {
    id: 'demo-spiderman',
    slug: 'figura-armable-spider-man',
    name: 'Figura armable Spider-Man',
    price: 16000,
    previousPrice: 19000,
    character: 'Spider-Man',
    presentation: 'Figura individual 8cm',
    pieces: 130,
    isLimitedEdition: false,
    description: 'El Trepamuros en version armable, compatible con bloques tipo LEGO.',
    brand: { name: 'Marvel' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 35 },
    images: [],
  },
  {
    id: 'demo-naruto',
    slug: 'figura-armable-naruto-uzumaki',
    name: 'Figura armable Naruto Uzumaki',
    price: 15000,
    previousPrice: 17000,
    character: 'Naruto Uzumaki',
    presentation: 'Figura individual 8cm',
    pieces: 115,
    isLimitedEdition: false,
    description: 'Naruto modo Sabio armable, pieza a pieza como un verdadero coleccionable estilo bloques.',
    brand: { name: 'Naruto' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 30 },
    images: [],
  },
  {
    id: 'demo-batman',
    slug: 'figura-armable-batman',
    name: 'Figura armable Batman',
    price: 16000,
    previousPrice: 19000,
    character: 'Batman',
    presentation: 'Figura individual 8cm',
    pieces: 132,
    isLimitedEdition: false,
    description: 'El Caballero de la Noche en version armable, con capa incluida.',
    brand: { name: 'DC' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 27 },
    images: [],
  },
  {
    id: 'demo-vengadores-set',
    slug: 'set-x4-vengadores',
    name: 'Set x4 Vengadores',
    price: 64000,
    previousPrice: 72000,
    character: 'Iron Man, Spider-Man, Thor, Capitan America',
    presentation: 'Set x4',
    pieces: 510,
    isLimitedEdition: true,
    description: 'Completa tu equipo de superheroes con este set x4 de los Vengadores.',
    brand: { name: 'Marvel' },
    category: { name: 'Funkos & Sets' },
    inventory: { stock: 9 },
    images: [],
  },
  {
    id: 'demo-jinx',
    slug: 'figura-armable-jinx',
    name: 'Figura armable Jinx',
    price: 16000,
    previousPrice: 18500,
    character: 'Jinx',
    presentation: 'Figura individual 8cm',
    pieces: 127,
    isLimitedEdition: false,
    description: 'Jinx de League of Legends y Arcane en version armable coleccionable.',
    brand: { name: 'League of Legends' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 24 },
    images: [],
  },
  {
    id: 'demo-ahsoka',
    slug: 'figura-armable-ahsoka-tano',
    name: 'Figura armable Ahsoka Tano',
    price: 16000,
    previousPrice: 18000,
    character: 'Ahsoka Tano',
    presentation: 'Figura individual 8cm',
    pieces: 120,
    isLimitedEdition: false,
    description: 'La Padawan mas querida de la saga en version armable estilo bloques.',
    brand: { name: 'Star Wars' },
    category: { name: 'Minifiguras únicas' },
    inventory: { stock: 23 },
    images: [],
  },
  {
    id: 'demo-llavero-minecraft',
    slug: 'llavero-armable-minecraft-espada',
    name: 'Llavero armable Minecraft Espada',
    price: 12000,
    previousPrice: undefined,
    character: 'Espada de diamante',
    presentation: 'Llavero armable',
    pieces: 40,
    isLimitedEdition: false,
    description: 'Llavero armable con forma de espada de diamante de Minecraft.',
    brand: { name: 'Minecraft' },
    category: { name: 'Llaveros' },
    inventory: { stock: 35 },
    images: [],
  },
];

export function getDemoProduct(slug: string) {
  return demoProducts.find((product) => product.slug === slug) ?? demoProducts[0];
}
